######################################################################
# Automatically generated by qmake (2.01a) Thu May 15 10:17:24 2008
######################################################################

QT += network

CONFIG += staticlib

win32:CONFIG += console

TEMPLATE = lib

TARGET = InterProcessSignalPropagator
DESTDIR = ./../lib
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += qinterprocesssignalpropagator.h
SOURCES += qinterprocesssignalpropagator.cpp
